version: "3"

services:
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
    links:
      - mongo
    networks:
      - back-coder-network
  mongo:
    image: mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"
    volumes:
      - /home/alkeops/Programacion/Coder/Dockers/mongodb/data:/data/db
      - /home/alkeops/Programacion/Coder/Dockers/mongodb/config:/data/configdb
    networks:
      - back-coder-network
  redis: 
    image: redis
    container_name: redis-coder
    ports:
      - "6379:6379"
    networks:
      - back-coder-network

networks:
  back-coder-network:
    driver: bridge
